# Generated by Django 5.2 on 2025-07-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appitem',
            name='apk_file',
            field=models.FileField(blank=True, null=True, upload_to='apk_files/'),
        ),
        migrations.AlterField(
            model_name='appitem',
            name='download_url',
            field=models.URLField(blank=True),
        ),
    ]
