# Generated by Django 5.2.4 on 2025-07-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appitem_apk_file_alter_appitem_download_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appitem',
            name='download_url',
        ),
    ]
