# Generated by Django 5.2.4 on 2025-07-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_appitem_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app_images/'),
        ),
    ]
